@url=http://localhost:4800/api

###
POST {{url}}/user/register
Content-Type: application/json

{
    "name": "Sherali",
    "username": "sherali",
    "password": "Sher1234",
    "salary": 3000000,
    "role": "admin",
    "phone": "+998905589204"
}

###

POST {{url}}/user/login
Content-Type: application/json

{
    "username": "sherali",
    "password": "Sher1234"
}

###

POST {{url}}/category
Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlNhYWQgVGFraGlyIiwidXNlcm5hbWUiOiJzYWFkdGFraGlyIiwicGhvbmUiOiIrOTk4OTA1Nzg5MjA0Iiwicm9sZSI6ImFkbWluIiwic2FsYXJ5IjoyMDAwMDAwLCJpbWFnZSI6bnVsbCwiaWF0IjoxNjk5NDY5OTkzLCJleHAiOjE3MDAwNzQ3OTN9.YpXA8UmOuagWexH1k55x26IsgHok6Di2Y_x2iyBrswM
Admin-Key: opa039jf0w4fnio;sa;f49jfsif;i;fnafdnfldf
Content-Type: application/json

{
    "name": "Breads",
    "desc": "this description"
}

###

DELETE {{url}}/category/4
Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlNhYWQgVGFraGlyIiwidXNlcm5hbWUiOiJzYWFkdGFraGlyIiwicGhvbmUiOiIrOTk4OTA1Nzg5MjA0Iiwicm9sZSI6ImFkbWluIiwic2FsYXJ5IjoyMDAwMDAwLCJpbWFnZSI6bnVsbCwiaWF0IjoxNjk5NDY5OTkzLCJleHAiOjE3MDAwNzQ3OTN9.YpXA8UmOuagWexH1k55x26IsgHok6Di2Y_x2iyBrswM
Admin-Key: opa039jf0w4fnio;sa;f49jfsif;i;fnafdnfldf

###

GET {{url}}/category

###

GET {{url}}/product

###

GET {{url}}/product?category_id=5

###

POST {{url}}/product
Admin-Key: opa039jf0w4fnio;sa;f49jfsif;i;fnafdnfldf
Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlNhYWQgVGFraGlyIiwidXNlcm5hbWUiOiJzYWFkdGFraGlyIiwicGhvbmUiOiIrOTk4OTA1Nzg5MjA0Iiwicm9sZSI6ImFkbWluIiwic2FsYXJ5IjoyMDAwMDAwLCJpbWFnZSI6bnVsbCwiaWF0IjoxNjk5NDY5OTkzLCJleHAiOjE3MDAwNzQ3OTN9.YpXA8UmOuagWexH1k55x26IsgHok6Di2Y_x2iyBrswM
Content-Type: application/json

{
    "name": "Coca Cola 1.5", 
    "price": 13000, 
    "category_id": 5, 
    "desc": "comment"
}