# env
@url=http://localhost:4800/api
@admin-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlNhYWQgVGFraGlyIiwidXNlcm5hbWUiOiJzYWFkdGFraGlyIiwicGhvbmUiOiIrOTk4OTA1Nzg5MjA0IiwiaWF0IjoxNzAxMTM2NTQyLCJleHAiOjE3MDE3NDEzNDJ9.V7ySs380_bNpvJ4609h4NDqlieae2xWHfPfOs2lLE2o
@admin-key=1234
@waiter-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwibmFtZSI6IkJvYnVyIFRveGlyb3YiLCJ1c2VybmFtZSI6ImJvYnVyIiwicGhvbmUiOiIrOTk4OTE5MTIzMTg3IiwiaWF0IjoxNzAxMTM1NzI2LCJleHAiOjE3MDE3NDA1MjZ9.SvkZ-7NbWoaYsnVhK6NCGA72il8B4GjIkMUrV8jJkYA

### test role apis
# get all roles
GET {{url}}/role
###
# post role
POST {{url}}/role
Admin-Key: {{admin-key}}
Content-Type: application/json

{ "name": "oshpaz" }

###
# put role
PUT {{url}}/role/3
Admin-Key: {{admin-key}}
Content-Type: application/json

{ "name": "chef"}
###
# delete role
DELETE {{url}}/role/3
Admin-Key: {{admin-key}}

### check user apis
# get all users
GET {{url}}/user
Access-Token: {{admin-token}}

###
# register user
POST {{url}}/user/register
Admin-Key: {{admin-key}}
Content-Type: application/json

{
    "name": "Bobur Toxirov",
    "username": "bobur",
    "password": "Saad1234",
    "salary": 3000000,
    "role_id": 2,
    "phone": "+998919123187",
    "email": "saadtakhir1@gmail.com",
    "joined_date": "24.11.2023T23:20:10Z"
}
###
# login user
POST {{url}}/user/login
Content-Type: application/json

{
    "username": "saadtakhir",
    "password": "Saad1234"
}

###
# get admin verify
GET {{url}}/user/admin
Admin-Key: {{admin-key}}

###
# get token verify
GET {{url}}/user/verify
Access-Token: {{waiter-token}}
###
# delete user
DELETE {{url}}/user/6
Admin-Key: {{admin-key}}
Access-Token: {{admin-token}}
###
# put user
PUT {{url}}/user/7
Admin-Key: {{admin-key}}
Access-Token: {{admin-token}}
Content-Type: application/json

{
    "name": "Bobur Toxirov",
    "username": "toxirov_bobur",
    "salary": 5000000,
    "role_id": 2,
    "phone": "+998919123187",
    "email": "toxirovbobur@gmail.com"
}
###
GET {{url}}/productinorder?order_id=5
Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlNhYWQgVGFraGlyIiwidXNlcm5hbWUiOiJzYWFkdGFraGlyIiwicGhvbmUiOiIrOTk4OTA1NTg5MjA0Iiwicm9sZV9pZCI6MSwic2FsYXJ5IjozMDAwMDAwLCJpbWFnZSI6bnVsbCwiaWF0IjoxNjk5ODk4NzQ4LCJleHAiOjE3MDA1MDM1NDh9.zv2T2W_RrVzS8eg1UiU0bUILI_MpebdnsTC0NloLbQw

###

POST {{url}}/productinorder
Content-Type: application/json
Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlNhYWQgVGFraGlyIiwidXNlcm5hbWUiOiJzYWFkdGFraGlyIiwicGhvbmUiOiIrOTk4OTA1NTg5MjA0Iiwicm9sZV9pZCI6MSwic2FsYXJ5IjozMDAwMDAwLCJpbWFnZSI6bnVsbCwiaWF0IjoxNjk5ODk4NzQ4LCJleHAiOjE3MDA1MDM1NDh9.zv2T2W_RrVzS8eg1UiU0bUILI_MpebdnsTC0NloLbQw

{
    "user_id": 1,
    "order_id": 1,
    "product_id": 1,
    "count": 2
}

###

GET {{url}}/order
Access-Token: {{admin-token}}

###

POST http://localhost:4800/api/order
Access-Token: {{admin-token}}
Content-Type: application/json

{
    "title": "Order 1",
    "room_id": 1,
    "desc": "izoh",
    "created_date": "27.11.2023T23:20:12.3Z"
}

###

GET {{url}}/order
Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlNhYWQgVGFraGlyIiwidXNlcm5hbWUiOiJzYWFkdGFraGlyIiwicGhvbmUiOiIrOTk4OTA1Nzg5MjA0Iiwicm9sZSI6ImFkbWluIiwic2FsYXJ5IjozMDAwMDAwLCJpbWFnZSI6bnVsbCwiaWF0IjoxNzAwNDEzOTk0LCJleHAiOjE3MDEwMTg3OTR9.kHBIPDbXXt9VABj_IBOydaBodHPyKvcdN0p3pmqoLTY

###

DELETE {{url}}/room/10
Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlNhYWQgVGFraGlyIiwidXNlcm5hbWUiOiJzYWFkdGFraGlyIiwicGhvbmUiOiIrOTk4OTA1NTg5MjA0Iiwicm9sZV9pZCI6MSwic2FsYXJ5IjozMDAwMDAwLCJpbWFnZSI6bnVsbCwiaWF0IjoxNjk5ODk4NzQ4LCJleHAiOjE3MDA1MDM1NDh9.zv2T2W_RrVzS8eg1UiU0bUILI_MpebdnsTC0NloLbQw
Admin-Key: 1234

###

POST {{url}}/room
Access-Token: {{admin-token}}
Admin-Key: 1234
Content-Type: application/json

{
    "name": "Zal 1",
    "desc": "Xona haqida malumot",
    "capacity": 40,
    "created_date": "27.11.2023T23:20:12.3Z"
}

###

GET {{url}}/room
Access-Token: {{admin-token}}


###

POST {{url}}/order
Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlNhYWQgVGFraGlyIiwidXNlcm5hbWUiOiJzYWFkdGFraGlyIiwicGhvbmUiOiIrOTk4OTA1NTg5MjA0Iiwicm9sZV9pZCI6MSwic2FsYXJ5IjozMDAwMDAwLCJpbWFnZSI6bnVsbCwiaWF0IjoxNjk5ODk4NzQ4LCJleHAiOjE3MDA1MDM1NDh9.zv2T2W_RrVzS8eg1UiU0bUILI_MpebdnsTC0NloLbQw
Content-Type: application/json

{
    "title": "Zakaz 3",
    "desc": null,
    "room_id": 1,
    "total_price": null
}

###

PATCH {{url}}/order/3/status
Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlNhYWQgVGFraGlyIiwidXNlcm5hbWUiOiJzYWFkdGFraGlyIiwicGhvbmUiOiIrOTk4OTA1NTg5MjA0Iiwicm9sZV9pZCI6MSwic2FsYXJ5IjozMDAwMDAwLCJpbWFnZSI6bnVsbCwiaWF0IjoxNjk5ODk4NzQ4LCJleHAiOjE3MDA1MDM1NDh9.zv2T2W_RrVzS8eg1UiU0bUILI_MpebdnsTC0NloLbQw
Content-Type: application/json

{
    "status": false
}

###

GET http://31.129.110.72:4800/api/product

###

GET {{url}}/productinorder
Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlNhYWQgVGFraGlyIiwidXNlcm5hbWUiOiJzYWFkdGFraGlyIiwicGhvbmUiOiIrOTk4OTA1NTg5MjA0Iiwicm9sZV9pZCI6MSwic2FsYXJ5IjozMDAwMDAwLCJpbWFnZSI6bnVsbCwiaWF0IjoxNjk5ODk4NzQ4LCJleHAiOjE3MDA1MDM1NDh9.zv2T2W_RrVzS8eg1UiU0bUILI_MpebdnsTC0NloLbQw

###

POST {{url}}/productinorder
Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlNhYWQgVGFraGlyIiwidXNlcm5hbWUiOiJzYWFkdGFraGlyIiwicGhvbmUiOiIrOTk4OTA1Nzg5MjA0Iiwicm9sZSI6ImFkbWluIiwic2FsYXJ5IjozMDAwMDAwLCJpbWFnZSI6bnVsbCwiaWF0IjoxNzAwNDEzOTk0LCJleHAiOjE3MDEwMTg3OTR9.kHBIPDbXXt9VABj_IBOydaBodHPyKvcdN0p3pmqoLTY
Content-Type: application/json

{
    "order_id": 2,
    "product_id": 3,
    "count": 2
}

###
GET {{url}}/role
Admin-Key: 1234
